# Generated by Django 5.0.4 on 2024-10-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_weeklyplan_plan_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='nutrition_info',
            field=models.JSONField(null=True),
        ),
    ]
