# Generated by Django 5.0.4 on 2024-10-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_mealrecord_calorie_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecord',
            name='openai_repeat',
        ),
    ]
