# Generated by Django 5.1.1 on 2024-10-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_mealrecord_openai_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_habits',
            field=models.TextField(null=True),
        ),
    ]
