# Generated by Django 5.1.1 on 2024-10-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_dietary_habits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_habits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
